# Generated by Django 6.0.5 on 2026-05-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book Title')),
                ('author', models.CharField(max_length=100, verbose_name='Book Author')),
                ('autor', models.CharField(max_length=100, verbose_name='Book Author')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Book Price')),
                ('description', models.TextField()),
                ('stock', models.BooleanField(default=True, verbose_name='Book Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Category Slug')),
            ],
        ),
    ]
