# Generated by Django 6.0.5 on 2026-06-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_book_options_alter_book_price_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="book",
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("can_add_book_stock", "Can add book stock"),
                    ("can_manage_books", "Can manage books"),
                    ("can_view_reports", "Can view reports"),
                ]
            },
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
