# Generated by Django 6.0.5 on 2026-07-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_remove_order_stripe_session_id_order_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Stripe session ID",
            ),
        ),
    ]
